[build]
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm dev"
  targetPort = 3000
  port = 8888
